version: '2'
services:
    web-build:
        build: 
            context: .
            dockerfile: BuildDockerFile
        image: "webbuild:base"
        tty: true
        working_dir: /app
        ports:
            - "8080:8080"
        volumes:
            -  "./src:/app"
        command: sh /app/build.sh
        links:
            - "web-service:ws"
        depends_on:
            - web-service
    web-service:
        build: 
            context: .
            dockerfile: ServiceDockerFile
        image: "webservice:base"
        ports:
            - "5000:5000"
        tty: true
        working_dir: /app
        command: sh /app/server.sh
#        command: sh /app/redisTest.sh
        volumes:
            -  "./src/serverApp:/app"
        links:
            - "data-cache"
    data-cache:
        image: redis:alpine
        command: redis-server --bind 0.0.0.0 --appendonly yes --requirepass redis
        container_name: redis
        ports: 
            - "6379:6379"
        volumes:
            -  "./src/redis/redis.conf:/usr/local/etc/redis/redis.conf"
            -  "./src/redis/data:/var/lib/redis"
    #   links:
    #     - "database-server:db"
    # database-server:
    #     image: mariadb
    #     command: mysqld --innodb-buffer-pool-size=20M
    #     env_file:
    #         - .env
    #     volumes:
    #         - "./src/mariaDB:/var/lib/mysql:rw"
    #     ports:
    #         - "3306:3306"