DATA_ENGINE = "DATA_ENGINE"
DATA_LOCATION = "DATA_LOCATION"
MYSQL_DATABASE = "MYSQL_DATABASE"
MYSQL_USER = "MYSQL_USER"
MYSQL_PASSWORD = "MYSQL_PASSWORD"
MYSQL_ROOT_PASSWORD = "MYSQL_ROOT_PASSWORD"

REDIS_HOST_FEATURE = "REDIS_HOST_FEATURE"
REDIS_PASSWORD_FEATURE = "REDIS_PASSWORD_FEATURE"
REDIS_PORT_FEATURE = "REDIS_PORT_FEATURE"
REDIS_DATABASE_FEATURE = "REDIS_DATABASE_FEATURE"

